steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/agape-sovereign/app', '.']
images:
  - 'gcr.io/agape-sovereign/app'
options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: 'projects/agape-sovereign/serviceAccounts/firebase-adminsdk-fbsvc@agape-sovereign.iam.gserviceaccount.com'
